// Code generated by aireyac. DO NOT EDIT.
package example

import (
	"github.com/aireya/aireya-go/wire"
)

type Status uint32

const (
	Status_ACTIVE Status = 1
	Status_INACTIVE Status = 2
)

type User struct {
	Id int64
	Name string
	Tags []string
}

func (m *User) Encode() []byte {
	enc := &wire.Encoder{}
	enc.WriteInt64(1, int64(m.Id))
	enc.WriteString(2, m.Name)
	return enc.Buf
}

func (m *User) Decode(buf []byte) error {
	dec := &wire.Decoder{Buf: buf}
	for !dec.IsAtEnd() {
		fieldNum, _, ok := dec.ReadTag()
		if !ok { break }
		switch fieldNum {
		case 1:
			val, _ := dec.ReadInt64()
			m.Id = int64(val)
		case 2:
			val, _ := dec.ReadString()
			m.Name = val
		case 3:
		}
	}
	return nil
}

type UserService interface {
	GetUser(req *User) (*User, error)
	StreamUsers(req *User) (chan *User, error)
}

