// Code generated by aireyac. DO NOT EDIT.
// Source: input.aya

#pragma once

#include <string>
#include <vector>
#include <cstdint>
#include <memory>
#include "aireya/wire_format.h"

namespace aireya {
namespace example {

enum class Status : uint32_t {
    ACTIVE = 1,
    INACTIVE = 2,
};

class User {
public:
    int64_t id;
    std::string name;
    std::vector<std::string> tags;

    // Aireya Serialization
    inline bool SerializeToArray(std::vector<uint8_t>& buf) const {
        ::aireya::wire::Encoder encoder(buf);
        encoder.WriteInt64(1, id);
        encoder.WriteString(2, name);
        return true;
    }

    inline bool ParseFromArray(const uint8_t* buf, size_t size) {
        ::aireya::wire::Decoder decoder(buf, size);
        uint32_t field_number;
        ::aireya::wire::WireType type;
        while (decoder.ReadTag(field_number, type)) {
            switch (field_number) {
                case 1: {
                    int64_t val;
                    if (!decoder.ReadInt64(val)) return false;
                    id = val;
                    break;
                }
                case 2: {
                    if (!decoder.ReadString(name)) return false;
                    break;
                }
                case 3: {
                    break;
                }
                default:
                    if (!decoder.SkipField(type)) return false;
                    break;
            }
        }
        return true;
    }
};

class UserService {
public:
    virtual ~UserService() = default;

    virtual int GetUser(const User& req, User* resp) = 0;
    virtual int StreamUsers(const User& req, /* Stream */ User* resp) = 0;
};

class UserServiceClient {
public:
    UserServiceClient(std::shared_ptr<::aireya::Connection> conn) : conn_(conn) {}

    int GetUser(const User& req, User* resp) {
        (void)resp; // Suppress unused warning for skeleton
        ::aireya::Frame frame;
        frame.type = ::aireya::FrameType::REQUEST;
        frame.metadata["rpc"] = "UserService.GetUser";
        req.SerializeToArray(frame.payload);
        conn_->SendFrame(frame);
        // TODO: Wait for response matching StreamID asynchronously
        return 0;
    }

    int StreamUsers(const User& req, User* resp) {
        (void)resp; // Suppress unused warning for skeleton
        ::aireya::Frame frame;
        frame.type = ::aireya::FrameType::REQUEST;
        frame.metadata["rpc"] = "UserService.StreamUsers";
        req.SerializeToArray(frame.payload);
        conn_->SendFrame(frame);
        // TODO: Wait for response matching StreamID asynchronously
        return 0;
    }

private:
    std::shared_ptr<::aireya::Connection> conn_;
};

} // namespace example
} // namespace aireya
