// Code generated by aireyac. DO NOT EDIT.
package aireya.example;

import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.CompletableFuture;

class AireyaWire {
    static void encodeVarint(ByteArrayOutputStream out, long val) {
        while (true) {
            int b = (int)(val & 0x7F);
            val >>>= 7;
            if (val == 0) { out.write(b); return; }
            out.write(b | 0x80);
        }
    }

    static long decodeVarint(ByteBuffer buf) {
        long result = 0; int shift = 0;
        while (buf.hasRemaining()) {
            int b = buf.get() & 0xFF;
            result |= (long)(b & 0x7F) << shift;
            if ((b & 0x80) == 0) break;
            shift += 7;
        }
        return result;
    }

    static void encodeTag(ByteArrayOutputStream out, int fieldNum, int wireType) {
        encodeVarint(out, ((long)fieldNum << 3) | wireType);
    }

    static int[] decodeTag(ByteBuffer buf) {
        long tag = decodeVarint(buf);
        return new int[]{(int)(tag >> 3), (int)(tag & 0x07)};
    }

    static void encodeBytes(ByteArrayOutputStream out, int fieldNum, byte[] data) {
        encodeTag(out, fieldNum, 2);
        encodeVarint(out, data.length);
        out.write(data, 0, data.length);
    }

    static byte[] decodeBytes(ByteBuffer buf) {
        int len = (int)decodeVarint(buf);
        byte[] data = new byte[len];
        buf.get(data);
        return data;
    }
}

public class User {
    public long id;
    public String name;
    public java.util.List<String> tags;

    public byte[] serialize() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        AireyaWire.encodeTag(out, 1, 0);
        AireyaWire.encodeVarint(out, (long)this.id);
        AireyaWire.encodeBytes(out, 2, this.name.getBytes(StandardCharsets.UTF_8));
        return out.toByteArray();
    }

    public static User deserialize(byte[] data) {
        User msg = new User();
        ByteBuffer buf = ByteBuffer.wrap(data);
        while (buf.hasRemaining()) {
            int[] tag = AireyaWire.decodeTag(buf);
            int fieldNum = tag[0], wireType = tag[1];
            switch (fieldNum) {
                case 1:
                    msg.id = AireyaWire.decodeVarint(buf); break;
                case 2:
                    msg.name = new String(AireyaWire.decodeBytes(buf), StandardCharsets.UTF_8); break;
                case 3:
                default:
                    switch (wireType) {
                        case 0: AireyaWire.decodeVarint(buf); break;
                        case 1: buf.position(buf.position() + 8); break;
                        case 2: { int l = (int)AireyaWire.decodeVarint(buf); buf.position(buf.position() + l); break; }
                        case 5: buf.position(buf.position() + 4); break;
                    } break;
            }
        }
        return msg;
    }
}

public interface UserService {
    CompletableFuture<User> GetUser(User req);
    CompletableFuture<User> StreamUsers(User req);
}

