# Code generated by aireyac. DO NOT EDIT.
import asyncio
from typing import List, Dict, Optional

class User:
    def __init__(self):
        self.id = None
        self.name = None
        self.tags = None

    def serialize(self) -> bytes:
        # TODO: Implement Aireya varint encoding
        return b''

class UserServiceClient:
    def __init__(self, channel):
        self.channel = channel

    async def GetUser(self, req: 'User') -> 'User':
        # TODO: Send frame over asyncio socket
        pass

    async def StreamUsers(self, req: 'User') -> 'User':
        # TODO: Send frame over asyncio socket
        pass

