// Code generated by aireyac. DO NOT EDIT.
#![allow(unused_imports)]
#![allow(dead_code)]

#[derive(Debug, Clone)]
pub struct User {
    pub id: i64,
    pub name: String,
    pub tags: Vec<String>,
}

impl User {
    pub fn serialize(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        // TODO: Call aireya_rust_core::wire::encode()
        buf
    }
}

#[async_trait::async_trait]
pub trait UserService {
    async fn getuser(&self, req: User) -> Result<User, aireya_core::Error>;
    async fn streamusers(&self, req: User) -> Result<User, aireya_core::Error>;
}

