// Code generated by aireyac. DO NOT EDIT.
package aireya.example;

import java.util.concurrent.CompletableFuture;

public class User {
    public long id;
    public String name;
    public java.util.List<String> tags;

    public byte[] serialize() {
        // TODO: Call AireyaWireEncoder
        return new byte[0];
    }
}

public interface UserService {
    CompletableFuture<User> GetUser(User req);
    CompletableFuture<User> StreamUsers(User req);
}

