// Code generated by aireyac. DO NOT EDIT.

// ─── Aireya Wire Codec ─────────────────────────────────
class AireyaWireEncoder {
    private buf: number[] = [];

    encodeVarint(val: number | bigint): void {
        let v = BigInt(val);
        do {
            let byte = Number(v & 0x7Fn);
            v >>= 7n;
            if (v > 0n) byte |= 0x80;
            this.buf.push(byte);
        } while (v > 0n);
    }

    encodeTag(fieldNum: number, wireType: number): void {
        this.encodeVarint((fieldNum << 3) | wireType);
    }

    encodeInt(fieldNum: number, val: number | bigint): void {
        this.encodeTag(fieldNum, 0);
        this.encodeVarint(val);
    }

    encodeString(fieldNum: number, val: string): void {
        const encoded = new TextEncoder().encode(val);
        this.encodeTag(fieldNum, 2);
        this.encodeVarint(encoded.length);
        for (const b of encoded) this.buf.push(b);
    }

    encodeBytes(fieldNum: number, val: Uint8Array): void {
        this.encodeTag(fieldNum, 2);
        this.encodeVarint(val.length);
        for (const b of val) this.buf.push(b);
    }

    finish(): Uint8Array { return new Uint8Array(this.buf); }
}

class AireyaWireDecoder {
    private buf: Uint8Array;
    private pos = 0;
    constructor(buf: Uint8Array) { this.buf = buf; }

    isAtEnd(): boolean { return this.pos >= this.buf.length; }

    decodeVarint(): bigint {
        let result = 0n; let shift = 0n;
        while (this.pos < this.buf.length) {
            const b = this.buf[this.pos++];
            result |= BigInt(b & 0x7F) << shift;
            if ((b & 0x80) === 0) break;
            shift += 7n;
        }
        return result;
    }

    decodeTag(): [number, number] {
        const tag = this.decodeVarint();
        return [Number(tag >> 3n), Number(tag & 7n)];
    }

    decodeBytes(): Uint8Array {
        const len = Number(this.decodeVarint());
        const data = this.buf.slice(this.pos, this.pos + len);
        this.pos += len;
        return data;
    }

    decodeString(): string {
        return new TextDecoder().decode(this.decodeBytes());
    }

    skipField(wireType: number): void {
        switch (wireType) {
            case 0: this.decodeVarint(); break;
            case 1: this.pos += 8; break;
            case 2: { const len = Number(this.decodeVarint()); this.pos += len; break; }
            case 5: this.pos += 4; break;
        }
    }
}

export interface User {
    id: bigint;
    name: string;
    tags: Array<string>;
}

export function encodeUser(msg: User): Uint8Array {
    const enc = new AireyaWireEncoder();
    enc.encodeInt(1, msg.id);
    enc.encodeString(2, msg.name);
    return enc.finish();
}

export function decodeUser(data: Uint8Array): User {
    const msg: User = {} as User;
    const dec = new AireyaWireDecoder(data);
    while (!dec.isAtEnd()) {
        const [fieldNum, wireType] = dec.decodeTag();
        switch (fieldNum) {
            case 1:
                msg.id = dec.decodeVarint(); break;
            case 2:
                msg.name = dec.decodeString(); break;
            case 3:
            default: dec.skipField(wireType); break;
        }
    }
    return msg;
}

export interface UserService {
    GetUser(req: User): Promise<User>;
    StreamUsers(req: User): Promise<User>;
}

