// Code generated by aireyac. DO NOT EDIT.
import { AireyaWireEncoder, AireyaWireDecoder } from '@aireya/core';

export interface User {
    id: bigint;
    name: string;
    tags: Array<string>;
}

export const UserSerializer = {
    encode(message: User): Uint8Array {
        const encoder = new AireyaWireEncoder();
        // TODO: Map fields
        return encoder.finish();
    }
};

export interface UserService {
    GetUser(req: User): Promise<User>;
    StreamUsers(req: User): Promise<User>;
}

