# Code generated by aireyac. DO NOT EDIT.
from __future__ import annotations
import struct
import asyncio
from dataclasses import dataclass, field
from typing import Optional

# ─── Aireya Wire Codec ─────────────────────────────────
def _encode_varint(val: int) -> bytes:
    buf = bytearray()
    val = val & 0xFFFFFFFFFFFFFFFF  # unsigned
    while True:
        byte = val & 0x7F
        val >>= 7
        if val == 0:
            buf.append(byte)
            return bytes(buf)
        buf.append(byte | 0x80)

def _decode_varint(data: memoryview, pos: int) -> tuple[int, int]:
    result = 0; shift = 0
    while pos < len(data):
        b = data[pos]; pos += 1
        result |= (b & 0x7F) << shift
        if (b & 0x80) == 0: break
        shift += 7
    return result, pos

def _encode_tag(field_num: int, wire_type: int) -> bytes:
    return _encode_varint((field_num << 3) | wire_type)

def _decode_tag(data: memoryview, pos: int) -> tuple[int, int, int]:
    tag, pos = _decode_varint(data, pos)
    return tag >> 3, tag & 0x07, pos

def _encode_bytes_field(field_num: int, val: bytes) -> bytes:
    return _encode_tag(field_num, 2) + _encode_varint(len(val)) + val

def _skip_field(data: memoryview, pos: int, wire_type: int) -> int:
    if wire_type == 0:
        _, pos = _decode_varint(data, pos)
    elif wire_type == 1: pos += 8
    elif wire_type == 2:
        length, pos = _decode_varint(data, pos)
        pos += length
    elif wire_type == 5: pos += 4
    return pos

# ─── Generated Messages ────────────────────────────────

@dataclass
class User:
    id: int = 0
    name: str = ''
    tags: list[str] = None

    def serialize(self) -> bytes:
        buf = bytearray()
        buf += _encode_tag(1, 0) + _encode_varint(self.id)
        buf += _encode_bytes_field(2, self.name.encode('utf-8'))
        return bytes(buf)

    @classmethod
    def deserialize(cls, data: bytes) -> 'User':
        msg = cls()
        view = memoryview(data)
        pos = 0
        while pos < len(view):
            field_num, wire_type, pos = _decode_tag(view, pos)
            if field_num == 1:
                msg.id, pos = _decode_varint(view, pos)
            elif field_num == 2:
                length, pos = _decode_varint(view, pos)
                msg.name = bytes(view[pos:pos+length]).decode('utf-8')
                pos += length
            elif field_num == 3:
            else:
                pos = _skip_field(view, pos, wire_type)
        return msg

class UserServiceClient:
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        self._reader = reader
        self._writer = writer
        self._stream_id = 1

    async def GetUser(self, req: 'User') -> 'User':
        payload = req.serialize()
        # Build Aireya frame: [4B len][8B magic][1B type][1B flags][4B stream_id][2B meta_len][meta][payload]
        meta = b'rpc\x00UserService.GetUser'
        frame_body = b'Aireyav1' + struct.pack('>BBIH', 0x00, 0x00, self._stream_id, len(meta)) + meta + payload
        frame = struct.pack('>I', len(frame_body)) + frame_body
        self._writer.write(frame)
        await self._writer.drain()
        self._stream_id += 2
        # Read response frame
        resp_len_bytes = await self._reader.readexactly(4)
        resp_len = struct.unpack('>I', resp_len_bytes)[0]
        resp_frame = await self._reader.readexactly(resp_len)
        meta_len = struct.unpack('>H', resp_frame[14:16])[0]
        resp_payload = resp_frame[16 + meta_len:]
        return User.deserialize(resp_payload)

    async def StreamUsers(self, req: 'User') -> 'User':
        payload = req.serialize()
        # Build Aireya frame: [4B len][8B magic][1B type][1B flags][4B stream_id][2B meta_len][meta][payload]
        meta = b'rpc\x00UserService.StreamUsers'
        frame_body = b'Aireyav1' + struct.pack('>BBIH', 0x00, 0x00, self._stream_id, len(meta)) + meta + payload
        frame = struct.pack('>I', len(frame_body)) + frame_body
        self._writer.write(frame)
        await self._writer.drain()
        self._stream_id += 2
        # Read response frame
        resp_len_bytes = await self._reader.readexactly(4)
        resp_len = struct.unpack('>I', resp_len_bytes)[0]
        resp_frame = await self._reader.readexactly(resp_len)
        meta_len = struct.unpack('>H', resp_frame[14:16])[0]
        resp_payload = resp_frame[16 + meta_len:]
        return User.deserialize(resp_payload)

