// Code generated by aireyac. DO NOT EDIT.
// Frontend Framework Adapters (React, Vue, Next.js, Electron)

import { useState, useEffect } from 'react';
import { ref, onMounted } from 'vue';
import { AireyaClient } from '@aireya/core';

export function useGetUser(req: any) {
    const [data, setData] = useState<any>(null);
    useEffect(() => {
        AireyaClient.call('UserService.GetUser', req).then(setData);
    }, [req]);
    return { data };
}

export function useGetUserVue(req: any) {
    const data = ref<any>(null);
    onMounted(async () => {
        data.value = await AireyaClient.call('UserService.GetUser', req);
    });
    return { data };
}

export function useStreamUsers(req: any) {
    const [data, setData] = useState<any>(null);
    useEffect(() => {
        AireyaClient.call('UserService.StreamUsers', req).then(setData);
    }, [req]);
    return { data };
}

export function useStreamUsersVue(req: any) {
    const data = ref<any>(null);
    onMounted(async () => {
        data.value = await AireyaClient.call('UserService.StreamUsers', req);
    });
    return { data };
}

