package gen_frontend

import (
	"bytes"
	"fmt"
	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator { return &Generator{file: file} }

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("// Frontend Framework Adapters (React, Vue, Next.js, Electron)\n\n")

	g.buf.WriteString("import { useState, useEffect } from 'react';\n")
	g.buf.WriteString("import { ref, onMounted } from 'vue';\n")
	g.buf.WriteString("import { AireyaClient } from '@aireya/core';\n\n")

	for _, s := range g.file.Services {
		for _, rpc := range s.RPCs {
			// React Hook
			g.buf.WriteString(fmt.Sprintf("export function use%s(req: any) {\n", rpc.Name))
			g.buf.WriteString("    const [data, setData] = useState<any>(null);\n")
			g.buf.WriteString("    useEffect(() => {\n")
			g.buf.WriteString(fmt.Sprintf("        AireyaClient.call('%s.%s', req).then(setData);\n", s.Name, rpc.Name))
			g.buf.WriteString("    }, [req]);\n")
			g.buf.WriteString("    return { data };\n")
			g.buf.WriteString("}\n\n")

			// Vue Composable
			g.buf.WriteString(fmt.Sprintf("export function use%sVue(req: any) {\n", rpc.Name))
			g.buf.WriteString("    const data = ref<any>(null);\n")
			g.buf.WriteString("    onMounted(async () => {\n")
			g.buf.WriteString(fmt.Sprintf("        data.value = await AireyaClient.call('%s.%s', req);\n", s.Name, rpc.Name))
			g.buf.WriteString("    });\n")
			g.buf.WriteString("    return { data };\n")
			g.buf.WriteString("}\n\n")
		}
	}
	return g.buf.String(), nil
}
