package gen_node

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToTS(t string) string {
	switch t {
	case "int32", "uint32", "float", "double": return "number"
	case "int64", "uint64": return "bigint"
	case "string": return "string"
	case "bool": return "boolean"
	case "bytes": return "Uint8Array"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("Array<%s>", mapTypeToTS(inner))
	}
	return t
}

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("import { AireyaWireEncoder, AireyaWireDecoder } from '@aireya/core';\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    %s: %s;\n", f.Name, mapTypeToTS(f.Type)))
		}
		g.buf.WriteString("}\n\n")
		
		g.buf.WriteString(fmt.Sprintf("export const %sSerializer = {\n", s.Name))
		g.buf.WriteString(fmt.Sprintf("    encode(message: %s): Uint8Array {\n", s.Name))
		g.buf.WriteString("        const encoder = new AireyaWireEncoder();\n")
		g.buf.WriteString("        // TODO: Map fields\n")
		g.buf.WriteString("        return encoder.finish();\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("};\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToTS(rpc.ReqType)
			respArg := mapTypeToTS(rpc.RespType)
			g.buf.WriteString(fmt.Sprintf("    %s(req: %s): Promise<%s>;\n", rpc.Name, reqArg, respArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
