package gen_node

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToTS(t string) string {
	switch t {
	case "int32", "uint32", "float", "double": return "number"
	case "int64", "uint64": return "bigint"
	case "string": return "string"
	case "bool": return "boolean"
	case "bytes": return "Uint8Array"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("Array<%s>", mapTypeToTS(inner))
	}
	return t
}

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n\n")

	// Emit self-contained wire codec
	g.buf.WriteString("// ─── Aireya Wire Codec ─────────────────────────────────\n")
	g.buf.WriteString("class AireyaWireEncoder {\n")
	g.buf.WriteString("    private buf: number[] = [];\n\n")
	g.buf.WriteString("    encodeVarint(val: number | bigint): void {\n")
	g.buf.WriteString("        let v = BigInt(val);\n")
	g.buf.WriteString("        do {\n")
	g.buf.WriteString("            let byte = Number(v & 0x7Fn);\n")
	g.buf.WriteString("            v >>= 7n;\n")
	g.buf.WriteString("            if (v > 0n) byte |= 0x80;\n")
	g.buf.WriteString("            this.buf.push(byte);\n")
	g.buf.WriteString("        } while (v > 0n);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    encodeTag(fieldNum: number, wireType: number): void {\n")
	g.buf.WriteString("        this.encodeVarint((fieldNum << 3) | wireType);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    encodeInt(fieldNum: number, val: number | bigint): void {\n")
	g.buf.WriteString("        this.encodeTag(fieldNum, 0);\n")
	g.buf.WriteString("        this.encodeVarint(val);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    encodeString(fieldNum: number, val: string): void {\n")
	g.buf.WriteString("        const encoded = new TextEncoder().encode(val);\n")
	g.buf.WriteString("        this.encodeTag(fieldNum, 2);\n")
	g.buf.WriteString("        this.encodeVarint(encoded.length);\n")
	g.buf.WriteString("        for (const b of encoded) this.buf.push(b);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    encodeBytes(fieldNum: number, val: Uint8Array): void {\n")
	g.buf.WriteString("        this.encodeTag(fieldNum, 2);\n")
	g.buf.WriteString("        this.encodeVarint(val.length);\n")
	g.buf.WriteString("        for (const b of val) this.buf.push(b);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    finish(): Uint8Array { return new Uint8Array(this.buf); }\n")
	g.buf.WriteString("}\n\n")

	g.buf.WriteString("class AireyaWireDecoder {\n")
	g.buf.WriteString("    private buf: Uint8Array;\n")
	g.buf.WriteString("    private pos = 0;\n")
	g.buf.WriteString("    constructor(buf: Uint8Array) { this.buf = buf; }\n\n")
	g.buf.WriteString("    isAtEnd(): boolean { return this.pos >= this.buf.length; }\n\n")
	g.buf.WriteString("    decodeVarint(): bigint {\n")
	g.buf.WriteString("        let result = 0n; let shift = 0n;\n")
	g.buf.WriteString("        while (this.pos < this.buf.length) {\n")
	g.buf.WriteString("            const b = this.buf[this.pos++];\n")
	g.buf.WriteString("            result |= BigInt(b & 0x7F) << shift;\n")
	g.buf.WriteString("            if ((b & 0x80) === 0) break;\n")
	g.buf.WriteString("            shift += 7n;\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("        return result;\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    decodeTag(): [number, number] {\n")
	g.buf.WriteString("        const tag = this.decodeVarint();\n")
	g.buf.WriteString("        return [Number(tag >> 3n), Number(tag & 7n)];\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    decodeBytes(): Uint8Array {\n")
	g.buf.WriteString("        const len = Number(this.decodeVarint());\n")
	g.buf.WriteString("        const data = this.buf.slice(this.pos, this.pos + len);\n")
	g.buf.WriteString("        this.pos += len;\n")
	g.buf.WriteString("        return data;\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    decodeString(): string {\n")
	g.buf.WriteString("        return new TextDecoder().decode(this.decodeBytes());\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    skipField(wireType: number): void {\n")
	g.buf.WriteString("        switch (wireType) {\n")
	g.buf.WriteString("            case 0: this.decodeVarint(); break;\n")
	g.buf.WriteString("            case 1: this.pos += 8; break;\n")
	g.buf.WriteString("            case 2: { const len = Number(this.decodeVarint()); this.pos += len; break; }\n")
	g.buf.WriteString("            case 5: this.pos += 4; break;\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("    }\n")
	g.buf.WriteString("}\n\n")

	// Generate interfaces & serializers
	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    %s: %s;\n", f.Name, mapTypeToTS(f.Type)))
		}
		g.buf.WriteString("}\n\n")

		// Encode
		g.buf.WriteString(fmt.Sprintf("export function encode%s(msg: %s): Uint8Array {\n", s.Name, s.Name))
		g.buf.WriteString("    const enc = new AireyaWireEncoder();\n")
		for _, f := range s.Fields {
			switch f.Type {
			case "int32", "uint32", "int64", "uint64", "bool":
				g.buf.WriteString(fmt.Sprintf("    enc.encodeInt(%s, msg.%s);\n", f.Tag, f.Name))
			case "string":
				g.buf.WriteString(fmt.Sprintf("    enc.encodeString(%s, msg.%s);\n", f.Tag, f.Name))
			case "bytes":
				g.buf.WriteString(fmt.Sprintf("    enc.encodeBytes(%s, msg.%s);\n", f.Tag, f.Name))
			}
		}
		g.buf.WriteString("    return enc.finish();\n")
		g.buf.WriteString("}\n\n")

		// Decode
		g.buf.WriteString(fmt.Sprintf("export function decode%s(data: Uint8Array): %s {\n", s.Name, s.Name))
		g.buf.WriteString(fmt.Sprintf("    const msg: %s = {} as %s;\n", s.Name, s.Name))
		g.buf.WriteString("    const dec = new AireyaWireDecoder(data);\n")
		g.buf.WriteString("    while (!dec.isAtEnd()) {\n")
		g.buf.WriteString("        const [fieldNum, wireType] = dec.decodeTag();\n")
		g.buf.WriteString("        switch (fieldNum) {\n")
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("            case %s:\n", f.Tag))
			switch f.Type {
			case "int32", "uint32":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = Number(dec.decodeVarint()); break;\n", f.Name))
			case "int64", "uint64":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = dec.decodeVarint(); break;\n", f.Name))
			case "bool":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = dec.decodeVarint() !== 0n; break;\n", f.Name))
			case "string":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = dec.decodeString(); break;\n", f.Name))
			case "bytes":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = dec.decodeBytes(); break;\n", f.Name))
			}
		}
		g.buf.WriteString("            default: dec.skipField(wireType); break;\n")
		g.buf.WriteString("        }\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("    return msg;\n")
		g.buf.WriteString("}\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToTS(rpc.ReqType)
			respArg := mapTypeToTS(rpc.RespType)
			g.buf.WriteString(fmt.Sprintf("    %s(req: %s): Promise<%s>;\n", rpc.Name, reqArg, respArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
