package gen_java

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToJava(t string) string {
	switch t {
	case "int32": return "int"
	case "int64": return "long"
	case "uint32": return "int"
	case "uint64": return "long"
	case "float": return "float"
	case "double": return "double"
	case "string": return "String"
	case "bool": return "boolean"
	case "bytes": return "byte[]"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("java.util.List<%s>", mapTypeToJava(inner))
	}
	return t
}

func boxedType(t string) string {
	switch t {
	case "int": return "Integer"
	case "long": return "Long"
	case "float": return "Float"
	case "double": return "Double"
	case "boolean": return "Boolean"
	}
	return t
}

func (g *Generator) Generate() (string, error) {
	pkgName := "io.aireya.generated"
	if g.file.Namespace != "" {
		pkgName = g.file.Namespace
	}

	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString(fmt.Sprintf("package %s;\n\n", pkgName))

	g.buf.WriteString("import java.io.ByteArrayOutputStream;\n")
	g.buf.WriteString("import java.nio.ByteBuffer;\n")
	g.buf.WriteString("import java.nio.charset.StandardCharsets;\n")
	g.buf.WriteString("import java.util.concurrent.CompletableFuture;\n\n")

	// Emit the AireyaWire helper class inline
	g.buf.WriteString("class AireyaWire {\n")
	g.buf.WriteString("    static void encodeVarint(ByteArrayOutputStream out, long val) {\n")
	g.buf.WriteString("        while (true) {\n")
	g.buf.WriteString("            int b = (int)(val & 0x7F);\n")
	g.buf.WriteString("            val >>>= 7;\n")
	g.buf.WriteString("            if (val == 0) { out.write(b); return; }\n")
	g.buf.WriteString("            out.write(b | 0x80);\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    static long decodeVarint(ByteBuffer buf) {\n")
	g.buf.WriteString("        long result = 0; int shift = 0;\n")
	g.buf.WriteString("        while (buf.hasRemaining()) {\n")
	g.buf.WriteString("            int b = buf.get() & 0xFF;\n")
	g.buf.WriteString("            result |= (long)(b & 0x7F) << shift;\n")
	g.buf.WriteString("            if ((b & 0x80) == 0) break;\n")
	g.buf.WriteString("            shift += 7;\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("        return result;\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    static void encodeTag(ByteArrayOutputStream out, int fieldNum, int wireType) {\n")
	g.buf.WriteString("        encodeVarint(out, ((long)fieldNum << 3) | wireType);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    static int[] decodeTag(ByteBuffer buf) {\n")
	g.buf.WriteString("        long tag = decodeVarint(buf);\n")
	g.buf.WriteString("        return new int[]{(int)(tag >> 3), (int)(tag & 0x07)};\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    static void encodeBytes(ByteArrayOutputStream out, int fieldNum, byte[] data) {\n")
	g.buf.WriteString("        encodeTag(out, fieldNum, 2);\n")
	g.buf.WriteString("        encodeVarint(out, data.length);\n")
	g.buf.WriteString("        out.write(data, 0, data.length);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    static byte[] decodeBytes(ByteBuffer buf) {\n")
	g.buf.WriteString("        int len = (int)decodeVarint(buf);\n")
	g.buf.WriteString("        byte[] data = new byte[len];\n")
	g.buf.WriteString("        buf.get(data);\n")
	g.buf.WriteString("        return data;\n")
	g.buf.WriteString("    }\n")
	g.buf.WriteString("}\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("public class %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    public %s %s;\n", mapTypeToJava(f.Type), f.Name))
		}

		// serialize
		g.buf.WriteString("\n    public byte[] serialize() {\n")
		g.buf.WriteString("        ByteArrayOutputStream out = new ByteArrayOutputStream();\n")
		for _, f := range s.Fields {
			switch f.Type {
			case "int32", "int64", "uint32", "uint64":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeTag(out, %s, 0);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeVarint(out, (long)this.%s);\n", f.Name))
			case "bool":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeTag(out, %s, 0);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeVarint(out, this.%s ? 1L : 0L);\n", f.Name))
			case "string":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeBytes(out, %s, this.%s.getBytes(StandardCharsets.UTF_8));\n", f.Tag, f.Name))
			case "bytes":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeBytes(out, %s, this.%s);\n", f.Tag, f.Name))
			case "float":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeTag(out, %s, 5);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        out.write(ByteBuffer.allocate(4).putFloat(this.%s).array(), 0, 4);\n", f.Name))
			case "double":
				g.buf.WriteString(fmt.Sprintf("        AireyaWire.encodeTag(out, %s, 1);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        out.write(ByteBuffer.allocate(8).putDouble(this.%s).array(), 0, 8);\n", f.Name))
			}
		}
		g.buf.WriteString("        return out.toByteArray();\n")
		g.buf.WriteString("    }\n\n")

		// deserialize
		g.buf.WriteString(fmt.Sprintf("    public static %s deserialize(byte[] data) {\n", s.Name))
		g.buf.WriteString(fmt.Sprintf("        %s msg = new %s();\n", s.Name, s.Name))
		g.buf.WriteString("        ByteBuffer buf = ByteBuffer.wrap(data);\n")
		g.buf.WriteString("        while (buf.hasRemaining()) {\n")
		g.buf.WriteString("            int[] tag = AireyaWire.decodeTag(buf);\n")
		g.buf.WriteString("            int fieldNum = tag[0], wireType = tag[1];\n")
		g.buf.WriteString("            switch (fieldNum) {\n")
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("                case %s:\n", f.Tag))
			switch f.Type {
			case "int32", "uint32":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = (int)AireyaWire.decodeVarint(buf); break;\n", f.Name))
			case "int64", "uint64":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = AireyaWire.decodeVarint(buf); break;\n", f.Name))
			case "bool":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = AireyaWire.decodeVarint(buf) != 0; break;\n", f.Name))
			case "string":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = new String(AireyaWire.decodeBytes(buf), StandardCharsets.UTF_8); break;\n", f.Name))
			case "bytes":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = AireyaWire.decodeBytes(buf); break;\n", f.Name))
			case "float":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = buf.getFloat(); break;\n", f.Name))
			case "double":
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = buf.getDouble(); break;\n", f.Name))
			}
		}
		// Unknown field skip
		g.buf.WriteString("                default:\n")
		g.buf.WriteString("                    switch (wireType) {\n")
		g.buf.WriteString("                        case 0: AireyaWire.decodeVarint(buf); break;\n")
		g.buf.WriteString("                        case 1: buf.position(buf.position() + 8); break;\n")
		g.buf.WriteString("                        case 2: { int l = (int)AireyaWire.decodeVarint(buf); buf.position(buf.position() + l); break; }\n")
		g.buf.WriteString("                        case 5: buf.position(buf.position() + 4); break;\n")
		g.buf.WriteString("                    } break;\n")
		g.buf.WriteString("            }\n")
		g.buf.WriteString("        }\n")
		g.buf.WriteString("        return msg;\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("}\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("public interface %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToJava(rpc.ReqType)
			respArg := boxedType(mapTypeToJava(rpc.RespType))
			g.buf.WriteString(fmt.Sprintf("    CompletableFuture<%s> %s(%s req);\n", respArg, rpc.Name, reqArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
