package gen_java

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToJava(t string) string {
	switch t {
	case "int32": return "int"
	case "int64": return "long"
	case "uint32": return "int"
	case "uint64": return "long"
	case "float": return "float"
	case "double": return "double"
	case "string": return "String"
	case "bool": return "boolean"
	case "bytes": return "byte[]"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("java.util.List<%s>", mapTypeToJava(inner))
	}
	return t
}

func (g *Generator) Generate() (string, error) {
	pkgName := "io.aireya.generated"
	if g.file.Namespace != "" {
		pkgName = g.file.Namespace
	}

	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString(fmt.Sprintf("package %s;\n\n", pkgName))
	
	g.buf.WriteString("import java.util.concurrent.CompletableFuture;\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("public class %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    public %s %s;\n", mapTypeToJava(f.Type), f.Name))
		}
		
		g.buf.WriteString("\n    public byte[] serialize() {\n")
		g.buf.WriteString("        // TODO: Call AireyaWireEncoder\n")
		g.buf.WriteString("        return new byte[0];\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("}\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("public interface %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToJava(rpc.ReqType)
			respArg := mapTypeToJava(rpc.RespType)
			g.buf.WriteString(fmt.Sprintf("    CompletableFuture<%s> %s(%s req);\n", respArg, rpc.Name, reqArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
