package gen_go

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{
		file: file,
	}
}

func (g *Generator) Generate() (string, error) {
	pkgName := "aireya_rpc"
	if g.file.Namespace != "" {
		parts := strings.Split(g.file.Namespace, ".")
		pkgName = parts[len(parts)-1]
	}

	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("package " + pkgName + "\n\n")

	g.buf.WriteString("import (\n")
	g.buf.WriteString("\t\"github.com/aireya/aireya-go/wire\"\n")
	g.buf.WriteString(")\n\n")

	g.generateEnums()
	g.generateStructs()
	g.generateServices()
	
	return g.buf.String(), nil
}

func (g *Generator) generateEnums() {
	for _, e := range g.file.Enums {
		g.buf.WriteString(fmt.Sprintf("type %s uint32\n\n", e.Name))
		g.buf.WriteString("const (\n")
		for _, v := range e.Values {
			g.buf.WriteString(fmt.Sprintf("\t%s_%s %s = %s\n", e.Name, v.Name, e.Name, v.Value))
		}
		g.buf.WriteString(")\n\n")
	}
}

func mapTypeToGo(t string) string {
	switch t {
	case "int32": return "int32"
	case "int64": return "int64"
	case "uint32": return "uint32"
	case "uint64": return "uint64"
	case "float": return "float32"
	case "double": return "float64"
	case "string": return "string"
	case "bool": return "bool"
	case "bytes": return "[]byte"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return "[]" + mapTypeToGo(inner)
	}
	return "*" + t // Custom structs are pointers in Go
}

func (g *Generator) generateStructs() {
	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
		for _, f := range s.Fields {
			goName := strings.Title(f.Name)
			goType := mapTypeToGo(f.Type)
			g.buf.WriteString(fmt.Sprintf("\t%s %s\n", goName, goType))
		}
		g.buf.WriteString("}\n\n")

		// Encode
		g.buf.WriteString(fmt.Sprintf("func (m *%s) Encode() []byte {\n", s.Name))
		g.buf.WriteString("\tenc := &wire.Encoder{}\n")
		for _, f := range s.Fields {
			goName := strings.Title(f.Name)
			if f.Type == "int64" || f.Type == "int32" || f.Type == "uint64" || f.Type == "uint32" {
				g.buf.WriteString(fmt.Sprintf("\tenc.WriteInt64(%s, int64(m.%s))\n", f.Tag, goName))
			} else if f.Type == "string" {
				g.buf.WriteString(fmt.Sprintf("\tenc.WriteString(%s, m.%s)\n", f.Tag, goName))
			}
		}
		g.buf.WriteString("\treturn enc.Buf\n")
		g.buf.WriteString("}\n\n")
		
		// Decode
		g.buf.WriteString(fmt.Sprintf("func (m *%s) Decode(buf []byte) error {\n", s.Name))
		g.buf.WriteString("\tdec := &wire.Decoder{Buf: buf}\n")
		g.buf.WriteString("\tfor !dec.IsAtEnd() {\n")
		g.buf.WriteString("\t\tfieldNum, _, ok := dec.ReadTag()\n")
		g.buf.WriteString("\t\tif !ok { break }\n")
		g.buf.WriteString("\t\tswitch fieldNum {\n")
		for _, f := range s.Fields {
			goName := strings.Title(f.Name)
			g.buf.WriteString(fmt.Sprintf("\t\tcase %s:\n", f.Tag))
			if f.Type == "int64" || f.Type == "int32" || f.Type == "uint64" || f.Type == "uint32" {
				g.buf.WriteString("\t\t\tval, _ := dec.ReadInt64()\n")
				g.buf.WriteString(fmt.Sprintf("\t\t\tm.%s = %s(val)\n", goName, mapTypeToGo(f.Type)))
			} else if f.Type == "string" {
				g.buf.WriteString("\t\t\tval, _ := dec.ReadString()\n")
				g.buf.WriteString(fmt.Sprintf("\t\t\tm.%s = val\n", goName))
			}
		}
		g.buf.WriteString("\t\t}\n")
		g.buf.WriteString("\t}\n")
		g.buf.WriteString("\treturn nil\n")
		g.buf.WriteString("}\n\n")
	}
}

func (g *Generator) generateServices() {
	for _, s := range g.file.Services {
		// Server Interface
		g.buf.WriteString(fmt.Sprintf("type %s interface {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToGo(rpc.ReqType)
			respArg := mapTypeToGo(rpc.RespType)
			if rpc.ReqStream { reqArg = "chan " + reqArg }
			if rpc.RespStream { respArg = "chan " + respArg }
			g.buf.WriteString(fmt.Sprintf("\t%s(req %s) (%s, error)\n", rpc.Name, reqArg, respArg))
		}
		g.buf.WriteString("}\n\n")
	}
}
