package gen_python

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator { return &Generator{file: file} }

func mapTypeToPy(t string) string {
	switch t {
	case "int32", "int64", "uint32", "uint64": return "int"
	case "float", "double": return "float"
	case "string": return "str"
	case "bool": return "bool"
	case "bytes": return "bytes"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("list[%s]", mapTypeToPy(inner))
	}
	return t
}

func pyDefault(t string) string {
	switch t {
	case "int32", "int64", "uint32", "uint64": return "0"
	case "float", "double": return "0.0"
	case "string": return "''"
	case "bool": return "False"
	case "bytes": return "b''"
	}
	return "None"
}

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("# Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("from __future__ import annotations\n")
	g.buf.WriteString("import struct\n")
	g.buf.WriteString("import asyncio\n")
	g.buf.WriteString("from dataclasses import dataclass, field\n")
	g.buf.WriteString("from typing import Optional\n\n")

	// Inline wire codec
	g.buf.WriteString("# ─── Aireya Wire Codec ─────────────────────────────────\n")
	g.buf.WriteString("def _encode_varint(val: int) -> bytes:\n")
	g.buf.WriteString("    buf = bytearray()\n")
	g.buf.WriteString("    val = val & 0xFFFFFFFFFFFFFFFF  # unsigned\n")
	g.buf.WriteString("    while True:\n")
	g.buf.WriteString("        byte = val & 0x7F\n")
	g.buf.WriteString("        val >>= 7\n")
	g.buf.WriteString("        if val == 0:\n")
	g.buf.WriteString("            buf.append(byte)\n")
	g.buf.WriteString("            return bytes(buf)\n")
	g.buf.WriteString("        buf.append(byte | 0x80)\n\n")

	g.buf.WriteString("def _decode_varint(data: memoryview, pos: int) -> tuple[int, int]:\n")
	g.buf.WriteString("    result = 0; shift = 0\n")
	g.buf.WriteString("    while pos < len(data):\n")
	g.buf.WriteString("        b = data[pos]; pos += 1\n")
	g.buf.WriteString("        result |= (b & 0x7F) << shift\n")
	g.buf.WriteString("        if (b & 0x80) == 0: break\n")
	g.buf.WriteString("        shift += 7\n")
	g.buf.WriteString("    return result, pos\n\n")

	g.buf.WriteString("def _encode_tag(field_num: int, wire_type: int) -> bytes:\n")
	g.buf.WriteString("    return _encode_varint((field_num << 3) | wire_type)\n\n")

	g.buf.WriteString("def _decode_tag(data: memoryview, pos: int) -> tuple[int, int, int]:\n")
	g.buf.WriteString("    tag, pos = _decode_varint(data, pos)\n")
	g.buf.WriteString("    return tag >> 3, tag & 0x07, pos\n\n")

	g.buf.WriteString("def _encode_bytes_field(field_num: int, val: bytes) -> bytes:\n")
	g.buf.WriteString("    return _encode_tag(field_num, 2) + _encode_varint(len(val)) + val\n\n")

	g.buf.WriteString("def _skip_field(data: memoryview, pos: int, wire_type: int) -> int:\n")
	g.buf.WriteString("    if wire_type == 0:\n")
	g.buf.WriteString("        _, pos = _decode_varint(data, pos)\n")
	g.buf.WriteString("    elif wire_type == 1: pos += 8\n")
	g.buf.WriteString("    elif wire_type == 2:\n")
	g.buf.WriteString("        length, pos = _decode_varint(data, pos)\n")
	g.buf.WriteString("        pos += length\n")
	g.buf.WriteString("    elif wire_type == 5: pos += 4\n")
	g.buf.WriteString("    return pos\n\n")

	g.buf.WriteString("# ─── Generated Messages ────────────────────────────────\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString("@dataclass\n")
		g.buf.WriteString(fmt.Sprintf("class %s:\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    %s: %s = %s\n", f.Name, mapTypeToPy(f.Type), pyDefault(f.Type)))
		}

		// serialize
		g.buf.WriteString("\n    def serialize(self) -> bytes:\n")
		g.buf.WriteString("        buf = bytearray()\n")
		for _, f := range s.Fields {
			switch f.Type {
			case "int32", "int64", "uint32", "uint64":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_tag(%s, 0) + _encode_varint(self.%s)\n", f.Tag, f.Name))
			case "bool":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_tag(%s, 0) + _encode_varint(1 if self.%s else 0)\n", f.Tag, f.Name))
			case "string":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_bytes_field(%s, self.%s.encode('utf-8'))\n", f.Tag, f.Name))
			case "bytes":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_bytes_field(%s, self.%s)\n", f.Tag, f.Name))
			case "float":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_tag(%s, 5) + struct.pack('<f', self.%s)\n", f.Tag, f.Name))
			case "double":
				g.buf.WriteString(fmt.Sprintf("        buf += _encode_tag(%s, 1) + struct.pack('<d', self.%s)\n", f.Tag, f.Name))
			}
		}
		g.buf.WriteString("        return bytes(buf)\n\n")

		// deserialize
		g.buf.WriteString("    @classmethod\n")
		g.buf.WriteString(fmt.Sprintf("    def deserialize(cls, data: bytes) -> '%s':\n", s.Name))
		g.buf.WriteString("        msg = cls()\n")
		g.buf.WriteString("        view = memoryview(data)\n")
		g.buf.WriteString("        pos = 0\n")
		g.buf.WriteString("        while pos < len(view):\n")
		g.buf.WriteString("            field_num, wire_type, pos = _decode_tag(view, pos)\n")
		for i, f := range s.Fields {
			prefix := "            if"
			if i > 0 { prefix = "            elif" }
			g.buf.WriteString(fmt.Sprintf("%s field_num == %s:\n", prefix, f.Tag))
			switch f.Type {
			case "int32", "int64", "uint32", "uint64":
				g.buf.WriteString(fmt.Sprintf("                msg.%s, pos = _decode_varint(view, pos)\n", f.Name))
			case "bool":
				g.buf.WriteString(fmt.Sprintf("                val, pos = _decode_varint(view, pos)\n"))
				g.buf.WriteString(fmt.Sprintf("                msg.%s = val != 0\n", f.Name))
			case "string":
				g.buf.WriteString("                length, pos = _decode_varint(view, pos)\n")
				g.buf.WriteString(fmt.Sprintf("                msg.%s = bytes(view[pos:pos+length]).decode('utf-8')\n", f.Name))
				g.buf.WriteString("                pos += length\n")
			case "bytes":
				g.buf.WriteString("                length, pos = _decode_varint(view, pos)\n")
				g.buf.WriteString(fmt.Sprintf("                msg.%s = bytes(view[pos:pos+length])\n", f.Name))
				g.buf.WriteString("                pos += length\n")
			case "float":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = struct.unpack_from('<f', view, pos)[0]; pos += 4\n", f.Name))
			case "double":
				g.buf.WriteString(fmt.Sprintf("                msg.%s = struct.unpack_from('<d', view, pos)[0]; pos += 8\n", f.Name))
			}
		}
		g.buf.WriteString("            else:\n")
		g.buf.WriteString("                pos = _skip_field(view, pos, wire_type)\n")
		g.buf.WriteString("        return msg\n\n")
	}

	// Service client stubs with real frame building
	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("class %sClient:\n", s.Name))
		g.buf.WriteString("    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):\n")
		g.buf.WriteString("        self._reader = reader\n")
		g.buf.WriteString("        self._writer = writer\n")
		g.buf.WriteString("        self._stream_id = 1\n\n")

		for _, rpc := range s.RPCs {
			g.buf.WriteString(fmt.Sprintf("    async def %s(self, req: '%s') -> '%s':\n", rpc.Name, rpc.ReqType, rpc.RespType))
			g.buf.WriteString("        payload = req.serialize()\n")
			g.buf.WriteString("        # Build Aireya frame: [4B len][8B magic][1B type][1B flags][4B stream_id][2B meta_len][meta][payload]\n")
			g.buf.WriteString(fmt.Sprintf("        meta = b'rpc\\x00%s.%s'\n", s.Name, rpc.Name))
			g.buf.WriteString("        frame_body = b'Aireyav1' + struct.pack('>BBIH', 0x00, 0x00, self._stream_id, len(meta)) + meta + payload\n")
			g.buf.WriteString("        frame = struct.pack('>I', len(frame_body)) + frame_body\n")
			g.buf.WriteString("        self._writer.write(frame)\n")
			g.buf.WriteString("        await self._writer.drain()\n")
			g.buf.WriteString("        self._stream_id += 2\n")
			g.buf.WriteString("        # Read response frame\n")
			g.buf.WriteString("        resp_len_bytes = await self._reader.readexactly(4)\n")
			g.buf.WriteString("        resp_len = struct.unpack('>I', resp_len_bytes)[0]\n")
			g.buf.WriteString("        resp_frame = await self._reader.readexactly(resp_len)\n")
			g.buf.WriteString("        meta_len = struct.unpack('>H', resp_frame[14:16])[0]\n")
			g.buf.WriteString("        resp_payload = resp_frame[16 + meta_len:]\n")
			g.buf.WriteString(fmt.Sprintf("        return %s.deserialize(resp_payload)\n\n", rpc.RespType))
		}
	}

	return g.buf.String(), nil
}
