package gen_python

import (
	"bytes"
	"fmt"
	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator { return &Generator{file: file} }

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("# Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("import asyncio\n")
	g.buf.WriteString("from typing import List, Dict, Optional\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("class %s:\n", s.Name))
		g.buf.WriteString("    def __init__(self):\n")
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("        self.%s = None\n", f.Name))
		}
		g.buf.WriteString("\n    def serialize(self) -> bytes:\n")
		g.buf.WriteString("        # TODO: Implement Aireya varint encoding\n")
		g.buf.WriteString("        return b''\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("class %sClient:\n", s.Name))
		g.buf.WriteString("    def __init__(self, channel):\n")
		g.buf.WriteString("        self.channel = channel\n\n")
		for _, rpc := range s.RPCs {
			g.buf.WriteString(fmt.Sprintf("    async def %s(self, req: '%s') -> '%s':\n", rpc.Name, rpc.ReqType, rpc.RespType))
			g.buf.WriteString("        # TODO: Send frame over asyncio socket\n")
			g.buf.WriteString("        pass\n\n")
		}
	}
	return g.buf.String(), nil
}
