package gen_rust

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToRust(t string) string {
	switch t {
	case "int32": return "i32"
	case "int64": return "i64"
	case "uint32": return "u32"
	case "uint64": return "u64"
	case "float": return "f32"
	case "double": return "f64"
	case "string": return "String"
	case "bool": return "bool"
	case "bytes": return "Vec<u8>"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("Vec<%s>", mapTypeToRust(inner))
	}
	return t
}

func wireTypeForRust(t string) string {
	switch t {
	case "int32", "int64", "uint32", "uint64", "bool":
		return "varint"
	case "float":
		return "fixed32"
	case "double":
		return "fixed64"
	default:
		return "length_delimited"
	}
}

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("#![allow(unused_imports)]\n#![allow(dead_code)]\n\n")

	// Emit the inline wire module so generated code is self-contained
	g.buf.WriteString("mod aireya_wire {\n")
	g.buf.WriteString("    pub fn encode_varint(buf: &mut Vec<u8>, mut val: u64) {\n")
	g.buf.WriteString("        loop {\n")
	g.buf.WriteString("            let byte = (val & 0x7F) as u8;\n")
	g.buf.WriteString("            val >>= 7;\n")
	g.buf.WriteString("            if val == 0 {\n")
	g.buf.WriteString("                buf.push(byte);\n")
	g.buf.WriteString("                return;\n")
	g.buf.WriteString("            }\n")
	g.buf.WriteString("            buf.push(byte | 0x80);\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    pub fn decode_varint(buf: &[u8], pos: &mut usize) -> u64 {\n")
	g.buf.WriteString("        let mut result: u64 = 0;\n")
	g.buf.WriteString("        let mut shift = 0;\n")
	g.buf.WriteString("        loop {\n")
	g.buf.WriteString("            if *pos >= buf.len() { break; }\n")
	g.buf.WriteString("            let byte = buf[*pos];\n")
	g.buf.WriteString("            *pos += 1;\n")
	g.buf.WriteString("            result |= ((byte & 0x7F) as u64) << shift;\n")
	g.buf.WriteString("            if byte & 0x80 == 0 { break; }\n")
	g.buf.WriteString("            shift += 7;\n")
	g.buf.WriteString("        }\n")
	g.buf.WriteString("        result\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    pub fn encode_tag(buf: &mut Vec<u8>, field_num: u32, wire_type: u8) {\n")
	g.buf.WriteString("        encode_varint(buf, ((field_num as u64) << 3) | (wire_type as u64));\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    pub fn decode_tag(buf: &[u8], pos: &mut usize) -> (u32, u8) {\n")
	g.buf.WriteString("        let tag = decode_varint(buf, pos);\n")
	g.buf.WriteString("        ((tag >> 3) as u32, (tag & 0x07) as u8)\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    pub fn encode_bytes(buf: &mut Vec<u8>, field_num: u32, data: &[u8]) {\n")
	g.buf.WriteString("        encode_tag(buf, field_num, 2);\n")
	g.buf.WriteString("        encode_varint(buf, data.len() as u64);\n")
	g.buf.WriteString("        buf.extend_from_slice(data);\n")
	g.buf.WriteString("    }\n\n")
	g.buf.WriteString("    pub fn decode_bytes(buf: &[u8], pos: &mut usize) -> Vec<u8> {\n")
	g.buf.WriteString("        let len = decode_varint(buf, pos) as usize;\n")
	g.buf.WriteString("        let data = buf[*pos..*pos + len].to_vec();\n")
	g.buf.WriteString("        *pos += len;\n")
	g.buf.WriteString("        data\n")
	g.buf.WriteString("    }\n")
	g.buf.WriteString("}\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString("#[derive(Debug, Clone, Default)]\n")
		g.buf.WriteString(fmt.Sprintf("pub struct %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    pub %s: %s,\n", f.Name, mapTypeToRust(f.Type)))
		}
		g.buf.WriteString("}\n\n")

		// serialize
		g.buf.WriteString(fmt.Sprintf("impl %s {\n", s.Name))
		g.buf.WriteString("    pub fn serialize(&self) -> Vec<u8> {\n")
		g.buf.WriteString("        let mut buf = Vec::new();\n")
		for _, f := range s.Fields {
			wt := wireTypeForRust(f.Type)
			switch wt {
			case "varint":
				g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_tag(&mut buf, %s, 0);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_varint(&mut buf, self.%s as u64);\n", f.Name))
			case "length_delimited":
				if f.Type == "string" {
					g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_bytes(&mut buf, %s, self.%s.as_bytes());\n", f.Tag, f.Name))
				} else if f.Type == "bytes" {
					g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_bytes(&mut buf, %s, &self.%s);\n", f.Tag, f.Name))
				}
			case "fixed32":
				g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_tag(&mut buf, %s, 5);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        buf.extend_from_slice(&self.%s.to_le_bytes());\n", f.Name))
			case "fixed64":
				g.buf.WriteString(fmt.Sprintf("        aireya_wire::encode_tag(&mut buf, %s, 1);\n", f.Tag))
				g.buf.WriteString(fmt.Sprintf("        buf.extend_from_slice(&self.%s.to_le_bytes());\n", f.Name))
			}
		}
		g.buf.WriteString("        buf\n")
		g.buf.WriteString("    }\n\n")

		// deserialize
		g.buf.WriteString("    pub fn deserialize(buf: &[u8]) -> Self {\n")
		g.buf.WriteString("        let mut msg = Self::default();\n")
		g.buf.WriteString("        let mut pos = 0usize;\n")
		g.buf.WriteString("        while pos < buf.len() {\n")
		g.buf.WriteString("            let (field_num, _wire_type) = aireya_wire::decode_tag(buf, &mut pos);\n")
		g.buf.WriteString("            match field_num {\n")
		for _, f := range s.Fields {
			wt := wireTypeForRust(f.Type)
			g.buf.WriteString(fmt.Sprintf("                %s => {\n", f.Tag))
			switch wt {
			case "varint":
				g.buf.WriteString("                    let v = aireya_wire::decode_varint(buf, &mut pos);\n")
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = v as %s;\n", f.Name, mapTypeToRust(f.Type)))
			case "length_delimited":
				if f.Type == "string" {
					g.buf.WriteString("                    let v = aireya_wire::decode_bytes(buf, &mut pos);\n")
					g.buf.WriteString(fmt.Sprintf("                    msg.%s = String::from_utf8_lossy(&v).to_string();\n", f.Name))
				} else {
					g.buf.WriteString("                    let v = aireya_wire::decode_bytes(buf, &mut pos);\n")
					g.buf.WriteString(fmt.Sprintf("                    msg.%s = v;\n", f.Name))
				}
			case "fixed32":
				g.buf.WriteString("                    let bytes: [u8; 4] = buf[pos..pos+4].try_into().unwrap();\n")
				g.buf.WriteString("                    pos += 4;\n")
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = f32::from_le_bytes(bytes);\n", f.Name))
			case "fixed64":
				g.buf.WriteString("                    let bytes: [u8; 8] = buf[pos..pos+8].try_into().unwrap();\n")
				g.buf.WriteString("                    pos += 8;\n")
				g.buf.WriteString(fmt.Sprintf("                    msg.%s = f64::from_le_bytes(bytes);\n", f.Name))
			}
			g.buf.WriteString("                }\n")
		}
		// Unknown field: skip by wire type (forward compat)
		g.buf.WriteString("                _ => {\n")
		g.buf.WriteString("                    match _wire_type {\n")
		g.buf.WriteString("                        0 => { aireya_wire::decode_varint(buf, &mut pos); }\n")
		g.buf.WriteString("                        1 => { pos += 8; }\n")
		g.buf.WriteString("                        2 => { let len = aireya_wire::decode_varint(buf, &mut pos) as usize; pos += len; }\n")
		g.buf.WriteString("                        5 => { pos += 4; }\n")
		g.buf.WriteString("                        _ => { break; }\n")
		g.buf.WriteString("                    }\n")
		g.buf.WriteString("                }\n")
		g.buf.WriteString("            }\n")
		g.buf.WriteString("        }\n")
		g.buf.WriteString("        msg\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("}\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString("#[async_trait::async_trait]\n")
		g.buf.WriteString(fmt.Sprintf("pub trait %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToRust(rpc.ReqType)
			respArg := mapTypeToRust(rpc.RespType)
			g.buf.WriteString(fmt.Sprintf("    async fn %s(&self, req: %s) -> Result<%s, Box<dyn std::error::Error>>;\n",
				strings.ToLower(rpc.Name), reqArg, respArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
