package gen_rust

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{file: file}
}

func mapTypeToRust(t string) string {
	switch t {
	case "int32": return "i32"
	case "int64": return "i64"
	case "uint32": return "u32"
	case "uint64": return "u64"
	case "float": return "f32"
	case "double": return "f64"
	case "string": return "String"
	case "bool": return "bool"
	case "bytes": return "Vec<u8>"
	}
	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("Vec<%s>", mapTypeToRust(inner))
	}
	return t
}

func (g *Generator) Generate() (string, error) {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("#![allow(unused_imports)]\n#![allow(dead_code)]\n\n")

	for _, s := range g.file.Structs {
		g.buf.WriteString("#[derive(Debug, Clone)]\n")
		g.buf.WriteString(fmt.Sprintf("pub struct %s {\n", s.Name))
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("    pub %s: %s,\n", f.Name, mapTypeToRust(f.Type)))
		}
		g.buf.WriteString("}\n\n")

		// Trait implementation for Serialization
		g.buf.WriteString(fmt.Sprintf("impl %s {\n", s.Name))
		g.buf.WriteString("    pub fn serialize(&self) -> Vec<u8> {\n")
		g.buf.WriteString("        let mut buf = Vec::new();\n")
		g.buf.WriteString("        // TODO: Call aireya_rust_core::wire::encode()\n")
		g.buf.WriteString("        buf\n")
		g.buf.WriteString("    }\n")
		g.buf.WriteString("}\n\n")
	}

	for _, s := range g.file.Services {
		g.buf.WriteString("#[async_trait::async_trait]\n")
		g.buf.WriteString(fmt.Sprintf("pub trait %s {\n", s.Name))
		for _, rpc := range s.RPCs {
			reqArg := mapTypeToRust(rpc.ReqType)
			respArg := mapTypeToRust(rpc.RespType)
			g.buf.WriteString(fmt.Sprintf("    async fn %s(&self, req: %s) -> Result<%s, aireya_core::Error>;\n", 
				strings.ToLower(rpc.Name), reqArg, respArg))
		}
		g.buf.WriteString("}\n\n")
	}

	return g.buf.String(), nil
}
