package gen_cpp

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/aireya/aireyac/parser"
)

type Generator struct {
	file *parser.File
	buf  bytes.Buffer
}

func New(file *parser.File) *Generator {
	return &Generator{
		file: file,
	}
}

func (g *Generator) Generate() (string, error) {
	g.generateHeader()
	g.generateNamespaceStart()
	g.generateEnums()
	g.generateStructs()
	g.generateServices()
	g.generateNamespaceEnd()
	return g.buf.String(), nil
}

func (g *Generator) generateHeader() {
	g.buf.WriteString("// Code generated by aireyac. DO NOT EDIT.\n")
	g.buf.WriteString("// Source: input.aya\n\n")
	g.buf.WriteString("#pragma once\n\n")
	g.buf.WriteString("#include <string>\n")
	g.buf.WriteString("#include <vector>\n")
	g.buf.WriteString("#include <cstdint>\n")
	g.buf.WriteString("#include <memory>\n")
	g.buf.WriteString("#include \"aireya/wire_format.h\"\n\n")
}

func (g *Generator) generateNamespaceStart() {
	if g.file.Namespace != "" {
		parts := strings.Split(g.file.Namespace, ".")
		for _, p := range parts {
			g.buf.WriteString(fmt.Sprintf("namespace %s {\n", p))
		}
		g.buf.WriteString("\n")
	}
}

func (g *Generator) generateNamespaceEnd() {
	if g.file.Namespace != "" {
		parts := strings.Split(g.file.Namespace, ".")
		for i := len(parts) - 1; i >= 0; i-- {
			g.buf.WriteString(fmt.Sprintf("} // namespace %s\n", parts[i]))
		}
	}
}

func (g *Generator) generateEnums() {
	for _, e := range g.file.Enums {
		g.buf.WriteString(fmt.Sprintf("enum class %s : uint32_t {\n", e.Name))
		for _, v := range e.Values {
			g.buf.WriteString(fmt.Sprintf("    %s = %s,\n", v.Name, v.Value))
		}
		g.buf.WriteString("};\n\n")
	}
}

func mapTypeToCpp(t string) string {
	switch t {
	case "int32":
		return "int32_t"
	case "int64":
		return "int64_t"
	case "uint32":
		return "uint32_t"
	case "uint64":
		return "uint64_t"
	case "float":
		return "float"
	case "double":
		return "double"
	case "string":
		return "std::string"
	case "bool":
		return "bool"
	case "bytes":
		return "std::vector<uint8_t>"
	}

	if strings.HasPrefix(t, "list<") && strings.HasSuffix(t, ">") {
		inner := t[5 : len(t)-1]
		return fmt.Sprintf("std::vector<%s>", mapTypeToCpp(inner))
	}

	// Assume custom struct or enum
	return t
}

func (g *Generator) generateStructs() {
	for _, s := range g.file.Structs {
		g.buf.WriteString(fmt.Sprintf("class %s {\n", s.Name))
		g.buf.WriteString("public:\n")

		// Fields
		for _, f := range s.Fields {
			cppType := mapTypeToCpp(f.Type)
			g.buf.WriteString(fmt.Sprintf("    %s %s;\n", cppType, f.Name))
		}
		g.buf.WriteString("\n")

		// Serialization interface (Aireya Binary Format)
		g.buf.WriteString("    // Aireya Serialization\n")
		g.buf.WriteString("    inline bool SerializeToArray(std::vector<uint8_t>& buf) const {\n")
		g.buf.WriteString("        ::aireya::wire::Encoder encoder(buf);\n")
		for _, f := range s.Fields {
			if f.Type == "int64" || f.Type == "int32" || f.Type == "uint64" || f.Type == "uint32" {
				g.buf.WriteString(fmt.Sprintf("        encoder.WriteInt64(%s, %s);\n", f.Tag, f.Name))
			} else if f.Type == "string" {
				g.buf.WriteString(fmt.Sprintf("        encoder.WriteString(%s, %s);\n", f.Tag, f.Name))
			}
			// Note: list/repeated fields left out for skeleton brevity
		}
		g.buf.WriteString("        return true;\n")
		g.buf.WriteString("    }\n\n")

		g.buf.WriteString("    inline bool ParseFromArray(const uint8_t* buf, size_t size) {\n")
		g.buf.WriteString("        ::aireya::wire::Decoder decoder(buf, size);\n")
		g.buf.WriteString("        uint32_t field_number;\n")
		g.buf.WriteString("        ::aireya::wire::WireType type;\n")
		g.buf.WriteString("        while (decoder.ReadTag(field_number, type)) {\n")
		g.buf.WriteString("            switch (field_number) {\n")
		for _, f := range s.Fields {
			g.buf.WriteString(fmt.Sprintf("                case %s: {\n", f.Tag))
			if f.Type == "int64" || f.Type == "int32" || f.Type == "uint64" || f.Type == "uint32" {
				g.buf.WriteString("                    int64_t val;\n")
				g.buf.WriteString("                    if (!decoder.ReadInt64(val)) return false;\n")
				g.buf.WriteString(fmt.Sprintf("                    %s = val;\n", f.Name))
			} else if f.Type == "string" {
				g.buf.WriteString(fmt.Sprintf("                    if (!decoder.ReadString(%s)) return false;\n", f.Name))
			}
			g.buf.WriteString("                    break;\n")
			g.buf.WriteString("                }\n")
		}
		g.buf.WriteString("                default:\n")
		g.buf.WriteString("                    if (!decoder.SkipField(type)) return false;\n")
		g.buf.WriteString("                    break;\n")
		g.buf.WriteString("            }\n")
		g.buf.WriteString("        }\n")
		g.buf.WriteString("        return true;\n")
		g.buf.WriteString("    }\n")

		g.buf.WriteString("};\n\n")
	}
}

func (g *Generator) generateServices() {
	for _, s := range g.file.Services {
		g.buf.WriteString(fmt.Sprintf("class %s {\n", s.Name))
		g.buf.WriteString("public:\n")
		g.buf.WriteString(fmt.Sprintf("    virtual ~%s() = default;\n\n", s.Name))

		for _, rpc := range s.RPCs {
			// For simplicity in the generated skeleton, we use a basic Status return
			// Real implementation would use futures/promises or a context object.
			
			reqArg := fmt.Sprintf("const %s& req", rpc.ReqType)
			if rpc.ReqStream {
				reqArg = fmt.Sprintf("/* Stream */ %s", rpc.ReqType) // placeholder
			}

			respArg := fmt.Sprintf("%s* resp", rpc.RespType)
			if rpc.RespStream {
				respArg = fmt.Sprintf("/* Stream */ %s* resp", rpc.RespType) 
			}

			g.buf.WriteString(fmt.Sprintf("    virtual int %s(%s, %s) = 0;\n", rpc.Name, reqArg, respArg))
		}
		g.buf.WriteString("};\n\n")

		// Client Stub
		g.buf.WriteString(fmt.Sprintf("class %sClient {\n", s.Name))
		g.buf.WriteString("public:\n")
		g.buf.WriteString(fmt.Sprintf("    %sClient(std::shared_ptr<::aireya::Connection> conn) : conn_(conn) {}\n\n", s.Name))

		for _, rpc := range s.RPCs {
			reqArg := fmt.Sprintf("const %s& req", rpc.ReqType)
			respArg := fmt.Sprintf("%s* resp", rpc.RespType)
			
			g.buf.WriteString(fmt.Sprintf("    int %s(%s, %s) {\n", rpc.Name, reqArg, respArg))
			g.buf.WriteString("        ::aireya::Frame frame;\n")
			g.buf.WriteString("        frame.type = ::aireya::FrameType::REQUEST;\n")
			g.buf.WriteString(fmt.Sprintf("        frame.metadata[\"rpc\"] = \"%s.%s\";\n", s.Name, rpc.Name))
			g.buf.WriteString("        req.SerializeToArray(frame.payload);\n")
			g.buf.WriteString("        conn_->SendFrame(frame);\n")
			g.buf.WriteString("        // Block until response frame arrives for this StreamID\n")
			g.buf.WriteString("        ::aireya::Frame resp_frame = conn_->RecvFrame(frame.stream_id);\n")
			g.buf.WriteString("        if (resp_frame.type == ::aireya::FrameType::ERROR) { return -1; }\n")
			g.buf.WriteString("        resp->ParseFromArray(resp_frame.payload.data(), resp_frame.payload.size());\n")
			g.buf.WriteString("        return 0;\n")
			g.buf.WriteString("    }\n\n")
		}
		
		g.buf.WriteString("private:\n")
		g.buf.WriteString("    std::shared_ptr<::aireya::Connection> conn_;\n")
		g.buf.WriteString("};\n\n")
	}
}
